name: Lints and formatting
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md

jobs:
  terraform-fmt:
    strategy:
      matrix:
        terraform-config: [ ".", "modules/cloudwatch-logs/", "modules/lb-logs/", "examples/", "tests/" ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.terraform-config }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: GitHub Action linting Terraform files
      uses: devops-infra/action-tflint@0.3
